<?php
require_once('tcpdf/tcpdf.php'); // Include TCPDF library

// Create new PDF document
$pdf = new TCPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('TELECARE+');
$pdf->SetTitle('Health Report');
$pdf->SetHeaderData('', 0, 'Health Monitoring Report', 'Generated by TELECARE+');

// Set font
$pdf->SetFont('helvetica', '', 12);
$pdf->AddPage();

// Dummy User Data (Replace with actual data from the database)
$user_name = "John Doe";
$date = date("Y-m-d");
$sugar_level = 180; // Example reading
$blood_pressure = "130/90";
$oxygen_level = "98%";
$heartbeat = "75 bpm";

// Generate PDF Content
$html = "
    <h2>Health Monitoring Report</h2>
    <p><strong>Name:</strong> $user_name</p>
    <p><strong>Date:</strong> $date</p>
    <hr>
    <h3>Health Readings:</h3>
    <p><strong>Blood Sugar:</strong> $sugar_level mg/dL</p>
    <p><strong>Blood Pressure:</strong> $blood_pressure</p>
    <p><strong>Oxygen Level:</strong> $oxygen_level</p>
    <p><strong>Heartbeat:</strong> $heartbeat</p>
";

// Add content to PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Output PDF (Download)
$pdf->Output('health_report.pdf', 'D'); // 'D' forces download

?>
